# Generated by Django 2.2.6 on 2019-11-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
    ]
